### ISSUE TITLE
Modify the Array prototype to include .smoosh

### ISSUE THREAD

**Issue by arswaw** [josiah-keller/use-adblockers#40]
We need to encourage TC39 to take the "smoosh" proposal seriously so I suggest creating the code for flattening an array and then alias it with smoosh.

**Comment by josiah-keller** [comment]
Wait, are you pro-smoosh?

**Comment by arswaw** [comment]
Are you not?

**Comment by josiah-keller** [comment]
You're in favor of renaming `flatten` to `smoosh`?  I mean, frankly I don't care that much, but if anything I'd be adding https://github.com/staltz/prevent-smoosh

**Comment by arswaw** [comment]
I think it's hilarious. Anyway, it's not part of the standard yet so let's poke fun at the controversy.

**Comment by josiah-keller** [comment]
Well I don't believe `flatten` is ever used in the codebase anyway, so while it is funny, I'm gonna have to close.
