### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by josiah-keller** [josiah-keller/use-adblockers#41]
Do SEO for keywords like "ads", "adblock", "adblocker"

**Comment by arswaw** [comment]
I want to note that, in case you didn't already know, the major search engines do not take into account meta keywords.

If that's not what this is about, then please ignore.

**Comment by josiah-keller** [comment]
SEO is obviously more than the meta tags.  If you've researched current SEO practices (I haven't in years) and want to take a stab at it, that'd be helpful

**Comment by arswaw** [comment]
Per [this](https://www.orbitmedia.com/blog/seo-best-practices/) website: 

1. Title could be changed to "Learn how to Block Malicious Ads | UseAdBlockers.org"
2. Meta description which might look like:

`<meta name="description" content="UseAdblockers.org is your one-stop shop for information on why you want to use adblockers, and how to install them."/>`

3. Let's make sure we don't repeat ourselves too much on the site, and our keywords, "blocking", "ads", "malicious", and "assistance" should be used no more than 4 times each.

4. Let's try including all the keywords we want to use in an h1 tag. An h2 tag should be used for each section.

5. Let's make sure any and all images, including icons have the appropriate accessibility attributes filled out including "alt="""

6. Ensure that none of our sections are more than three sentences long.

That should be enough to cover the basics.
