### ISSUE TITLE
Desktop Safari recommendation link no longer works

### ISSUE THREAD

**Issue by josiah-keller** [josiah-keller/use-adblockers#61]
It's supposed to be a direct link but the link is broken and now just takes you to an overview of all Safari extensions in the App Store.

**Comment by arswaw** [comment]
Assuming they're the links to uBlock, it seems to work just fine for me.

**Comment by josiah-keller** [comment]
@arswaw Really?  If I click the link in Safari it just pops the App Store at the main "Safari Extensions" page, not to the uBlock Origin page.  However, my only macOS machine is still on High Sierra, so maybe that's it.
